import { PRODUCTS, TAG } from "constants/images";

export const PRODUCTS_LIST = [
  {
    id: "p1",
    name: "RƯỢU VANG ĐÀ LẠT",
    link: PRODUCTS.P1,
    original: "370000",
    price: "480000",
    tag: TAG.HOT,
  },
  {
    id: "p2",
    name: "RƯỢU VANG HÀ LAN",
    link: PRODUCTS.P2,
    original: "370000",
    price: "480000",
    tag: TAG.HOT,
  },
  {
    id: "p3",
    name: "RƯỢU VANG HÀ LAN",
    link: PRODUCTS.P3,
    original: "370000",
    price: "480000",
    tag: TAG.NEW,
  },
  {
    id: "p4",
    name: "RƯỢU VANG HÀ LAN",
    link: PRODUCTS.P4,
    original: "370000",
    price: "480000",
    tag: TAG.NEW,
  },
  {
    id: "p5",
    name: "RƯỢU VANG HÀ LAN",
    link: PRODUCTS.P5,
    original: "370000",
    price: "480000",
    tag: TAG.SALE,
  },
  {
    id: "p6",
    name: "RƯỢU VANG HÀ LAN",
    link: PRODUCTS.P6,
    original: "370000",
    price: "480000",
    tag: TAG.SALE,
  },
  {
    id: "p7",
    name: "RƯỢU VANG HÀ LAN",
    link: PRODUCTS.P7,
    original: "370000",
    price: "480000",
    tag: TAG.SALE,
  },
  {
    id: "p8",
    name: "RƯỢU VANG HÀ LAN",
    link: PRODUCTS.P8,
    original: "370000",
    price: "480000",
    tag: TAG.SALE,
  },
];
